export function getVariables() {
	return [
		{ variableId: 'camera_name', name: 'Camera friendly name' },
		{ variableId: 'host', name: 'Camera IP address' },
		{ variableId: 'connected', name: 'Connected (true/false)' },
		{ variableId: 'onvif_ready', name: 'ONVIF ready (true/false) — needed for presets' },
		{ variableId: 'last_preset', name: 'Last recalled preset' },
		{ variableId: 'power', name: 'Power state (on/off)' },
		{ variableId: 'af', name: 'Auto-focus state (on/off)' },
		{ variableId: 'exposure_mode', name: 'Exposure mode name' },
		{ variableId: 'wb_mode', name: 'White-balance mode name' },
		{ variableId: 'gain', name: 'Gain value' },
		{ variableId: 'iris', name: 'Iris raw index (0-13)' },
		{ variableId: 'iris_fstop', name: 'Iris f-stop label (Off, f1.6...f32.0)' },
		{ variableId: 'shutter', name: 'Shutter value' },
		{ variableId: 'exposure_compensation', name: 'Exposure Compensation (-7 to +7, 0 = neutral)' },
		{ variableId: 'exposure_compensation_mode', name: 'Exposure Compensation Mode (on = Manual, off = Auto)' },
		{ variableId: 'zoom_position', name: 'Zoom position (0-16384)' },
		{ variableId: 'zoom_percent', name: 'Zoom position as percent (0=wide, 100=tele)' },
		{ variableId: 'focus_position', name: 'Focus position (0-16384)' },
		{ variableId: 'focus_percent', name: 'Focus position as percent (0=near, 100=far)' },
		{ variableId: 'focus_mode', name: 'Focus mode (Auto / Manual / One-Push / Locked)' },
		{ variableId: 'backlight', name: 'Backlight compensation (on/off)' },
		{ variableId: 'pan_position', name: 'Pan position (raw VISCA units)' },
		{ variableId: 'tilt_position', name: 'Tilt position (raw VISCA units)' },
		{ variableId: 'pan_degrees', name: 'Pan position in degrees (Home = 0°)' },
		{ variableId: 'tilt_degrees', name: 'Tilt position in degrees (Home = 0°)' },
		{ variableId: 'color_temp', name: 'Current color temperature (K)' },
		{ variableId: 'warmth', name: 'Warmth offset (-64 cool ↔ +64 warm, 0 neutral)' },
		{ variableId: 'preset_save_index', name: 'Save-rotary current preset index (turn to scroll, push to save)' },
		{ variableId: 'preset_recall_index', name: 'Recall-rotary current preset index (turn to scroll, push to recall)' },
		{ variableId: 'image_flip', name: 'Image Flip state (on = upside-down, off = normal)' },
		{ variableId: 'image_mirror', name: 'Image Mirror state (on = LR reversed, off = normal)' },
	]
}
